on: 
  workflow_dispatch:

name: Addons Data Update

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ScratchAddons/Website
        uses: actions/checkout@v2
        with:
          path: website
      - name: Checkout ScratchAddons/addons-data-updater
        uses: actions/checkout@v2
        with:
          repository: ScratchAddons/addons-data-updater
      - name: Install dependencies
        run: |
          npm install
      - name: Update addons data
        run: |
          npm start
      - name: Generate token 
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update addons data
          branch: create-pull-request/changelog
          committer: scratchaddons-bot[bot] <73682299+scratchaddons-bot[bot]@users.noreply.github.com>
          delete-branch: true
          path: ./website 
          title: Update addons data
          body: |
            This updates the addons data based on the main repo.

            It is recommended to do a rebase merge than other methods. Also, make sure to not merge something that isn't released yet!
