on: 
  workflow_dispatch:

name: Addons Data Update

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ScratchAddons/Website
        uses: actions/checkout@v2
      - name: Checkout ScratchAddons/addons-data-updater
        uses: actions/checkout@v2
        with:
          repository: ScratchAddons/addons-data-updater
          ref: fix-adu # remove before master
          path: script
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x 
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install --prefix script
      - name: Update addons data
        run: npm start --prefix script
      - name: Create commit
        uses: EndBug/add-and-commit@v5 # You can change this to use a specific version
        with:
          add: ./site/_data/addons.json
          message: Update addons data
          author_name: scratchaddons-bot[bot]
          author_email: 73682299+scratchaddons-bot[bot]@users.noreply.github.com
          push: false
      - name: Generate token 
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: create-pull-request/changelog
          delete-branch: true
          title: Update addons data
          body: |
            This updates the addons data based on the main repo.

            It is recommended to do a rebase merge than other methods. Also, make sure to not merge something that isn't released yet!
